name: Install and run example.py
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:

jobs:
  install_pip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python3 -m venv .venv
      - run: source .venv/bin/activate
      - run: pip install git+https://github.com/TheLovinator1/sitemap-parser.git
      - run: curl -sSL https://raw.githubusercontent.com/TheLovinator1/sitemap-parser/master/example.py -o example.py
      - run: python3 example.py
